config/routes.rb
Timevault::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :pomodoros, only: [:index, :create, :update, :destroy]

  resources :tasks

  resources :repositories, only: [:index, :create, :destroy]

  root :to => "main_pages#home"

  match '/about' => 'main_pages#about',
        as: :about

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user, inverse_of: :tasks
  has_many :task_commits
  has_many  :commits,
            through: :task_commits,
            dependent: :destroy,
            inverse_of: :tasks
            
  accepts_nested_attributes_for :commits,
                                reject_if: :all_blank,
                                allow_destroy: true

  validates_presence_of :user

  validates_presence_of :name
  validates_presence_of :start

  validates_datetime  :start,
                      after: lambda { 30.years.ago },
                      before_message: "date is too long ago"
  validates_datetime  :start,
                      before: lambda { (DateTime.now + 30.years) },
                      after_message: "date is too far in the future"

  validates_datetime  :end,
                      after: lambda { 30.years.ago },
                      before_message: "date is too long ago",
                      allow_blank: true

  validates_datetime  :end,
                      before: lambda { (DateTime.now + 30.years) },
                      after_message: "date is too far in the future",
                      allow_blank: true

  attr_accessible :description, :end, :name, :start, :commits_attributes

  class << self

    def descending_start_date
      order("start DESC")
    end
    
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  helper_method :get_current_time

  # GET /tasks
  # GET /tasks.json
  def index
    page_num = params[:page].to_i
    @tasks = current_user.tasks.descending_start_date.page(page_num).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks}
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task}
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = current_user.tasks.new
    @commit = @task.commits.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task}
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def edit
    @task = current_user.tasks.find(params[:id])
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.'}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: 'Task was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  def get_current_time
    DateTime.now.strftime('%d/%m/%Y %I:%M:%S %p')
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_commit_fields.html.erb
<div class="nested-fields">
  <%= f.input :sha1 %>
  <%= f.input :repository_id, collection: @task.user.repositories %>
  <%= link_to_remove_association "Remove Commit", f, :class => "btn btn-small" %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :description, input_html: { cols: 60, rows: 3 } %>

  <%= f.input :start,
    as: :string,
    wrapper_html: {id: 'task_start'},
    input_html: { :'data-format' => "dd/MM/yyyy HH:mm:ss PP", placeholder: get_current_time },
    :wrapper => :datepicker %>

  <%= f.input :end,
    as: :string,
    wrapper_html: {id: 'task_end'},
    input_html: { :'data-format' => "dd/MM/yyyy HH:mm:ss PP", placeholder: get_current_time },
    :wrapper => :datepicker %>

  <h3>Commits</h3>
  <div id="commits">
    <%= f.simple_fields_for :commits do |commit| %>
      <%= render 'commit_fields', f: commit %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Commit', f, :commits, :class => "btn btn-small" %>
    </div>
  </div>

  <div class="well">
    <%= f.button :submit, :class => "btn-primary" %>
    <small>* Indicates required field</small>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= javascript_tag do %>
  window.task = <%= raw @task.to_json %>
<% end %>
<div class="nav_active" id="edit-task">
 <%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<div class="nav_active" id="all_tasks">
  <%= paginate @tasks %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Task</th>
        <th>Start</th>
        <th>End</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
    <% @tasks.each do |task| %>
      <% if task.end.present? %>
        <tr>
      <% else %>
        <tr class="warning">
      <% end %>
        <td>
          <div class="btn-group">
            <%= link_to( '<i class="icon-edit icon-white"></i> '.html_safe + task.name, edit_task_path(task), class: "btn btn-primary") %>
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to('<i class="icon-eye-open"></i> '.html_safe + "Show", task) %></li>
              <li><%= link_to('<i class="icon-remove"></i> '.html_safe + "Delete", task, method: :delete, data: { confirm: 'Are you sure?' } ) %></li>
            </ul>
          </div>
        </td>
        <td><%= task.start.strftime("%e %b %l:%M %p") %></td>
        <% if task.end.present? %>
          <td><%= task.end.strftime("%e %b %l:%M %p") %></td>
        <% else %>
          <td><%= link_to( "Add Ending", edit_task_path(task), class: "btn btn-small btn-warning") %></td>
        <% end %>
        <td>
          <% if task.end.present? %>
            <%= distance_of_time_in_words(task.start, task.end) %>
          <% else %>
             - 
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class="nav_active" id="add_task">
  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<ul>
  <li>Name: <%= @task.name %></li>
  <li>Description: <%= @task.description %></li>
  <li>Start: <%= @task.start %></li>
  <li>End: <%= @task.end %></li>
  <% @task.commits.each do |commit| %>
    <li> SHA1: <%=commit.sha1%></li>
    <li> Repo: <%=commit.repository.name%></li>
    <% if commit.repository.url.present? %>
      <% url = commit.repository.url %>
      <% url << '/' unless url =~ /\/$/ %>
      <% commit_url = "#{url}commit/#{commit.sha1}" %>
      <li><%= link_to "Commit URL", commit_url, target: "_blank" %></li>
    <% end %>
  <% end %>
</ul>
<%= button_to('Delete', @task, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } ) %>