config/routes.rb
Timevault::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :pomodoros, only: [:index, :create, :update, :destroy]

  resources :tasks

  resources :repositories, only: [:index, :create, :destroy]

  root :to => "main_pages#home"

  match '/about' => 'main_pages#about',
        as: :about

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<%= link_to "TimeVault", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li id="add_task">
    <%= link_to "New Task", new_task_path %>
    </li>
    <li id="all_tasks">
    <%= link_to "Tasks", tasks_path %>
    </li>
  <% else %>
    <li id="login">
    <%= link_to('Login', new_user_session_path)  %>
    </li>
    <li id="sign_up">
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>
<div class="nav-collapse collapse">
  <ul class="nav">
    <% if user_signed_in? %>
      <li id="all_repositories">
      <%= link_to "Manage Repositories", repositories_path %>
      </li>
      <li id="all_pomodoros">
      <%= link_to "Pomodoros", pomodoros_path %>
      </li>
      <li id="edit_account">
      <%= link_to('Edit account', edit_user_registration_path) %>
      </li>
      <%- if current_user.admin? -%>
        <li><%= link_to('Admin', rails_admin_path) %></li>
      <%- end -%>
      <li id="logout">
      <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
      </li>
    <% end %>
    <li id="about">
    <%= link_to('About', about_path) %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TimeVault" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40861899-1', 'gotimevault.com');
  ga('send', 'pageview');

  </script>
  </body>
</html>